CreateThread(function()
	LaPuertaBlip = AddBlipForCoord(Config.BoatSpawnLocation.LaPuerta)
	SetBlipSprite(LaPuertaBlip, 317)
	SetBlipDisplay(LaPuertaBlip, 4)
	SetBlipScale(LaPuertaBlip, 0.5)
	SetBlipColour(LaPuertaBlip, 74)
    SetBlipAsShortRange(LaPuertaBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fishing")
    EndTextCommandSetBlipName(LaPuertaBlip)


	PaletoCoveBlip = AddBlipForCoord(Config.BoatSpawnLocation.PaletoCove)
	SetBlipSprite(PaletoCoveBlip, 317)
	SetBlipDisplay(PaletoCoveBlip, 4)
	SetBlipScale(PaletoCoveBlip, 0.5)
	SetBlipColour(PaletoCoveBlip, 74)
    SetBlipAsShortRange(Blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fishing")
    EndTextCommandSetBlipName(PaletoCoveBlip)

	ElGordoBlip = AddBlipForCoord(Config.BoatSpawnLocation.ElGordo)
	SetBlipSprite(ElGordoBlip, 317)
	SetBlipDisplay(ElGordoBlip, 4)
	SetBlipScale(ElGordoBlip, 0.5)
	SetBlipColour(ElGordoBlip, 74)
    SetBlipAsShortRange(ElGordoBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fishing")
    EndTextCommandSetBlipName(ElGordoBlip)

	ActDamBlip = AddBlipForCoord(Config.BoatSpawnLocation.ActDam)
	SetBlipSprite(ActDamBlip, 317)
	SetBlipDisplay(ActDamBlip, 4)
	SetBlipScale(ActDamBlip, 0.5)
	SetBlipColour(ActDamBlip, 74)
    SetBlipAsShortRange(ActDamBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fishing")
    EndTextCommandSetBlipName(ActDamBlip)

	AlamoSeaBlip = AddBlipForCoord(Config.BoatSpawnLocation.AlamoSea)
	SetBlipSprite(AlamoSeaBlip, 317)
	SetBlipDisplay(AlamoSeaBlip, 4)
	SetBlipScale(AlamoSeaBlip, 0.5)
	SetBlipColour(AlamoSeaBlip, 74)
    SetBlipAsShortRange(AlamoSeaBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fishing")
    EndTextCommandSetBlipName(AlamoSeaBlip)

	PearlsSellsBlip = AddBlipForCoord(Config.PearlsSellsBlip)
	SetBlipSprite(PearlsSellsBlip, 68)
	SetBlipDisplay(PearlsSellsBlip, 4)
	SetBlipScale(PearlsSellsBlip, 0.7)
	SetBlipColour(PearlsSellsBlip, 74)
    SetBlipAsShortRange(PearlsSellsBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Fish Sells")
    EndTextCommandSetBlipName(PearlsSellsBlip)
end)
