			['ast'] = {
				['name'] = 'Aston Martin',
				['brand'] = 'Aston Martin',
				['model'] = 'ast',
				['price'] = 280000,
				['category'] = 'import',
				['hash'] = `ast`,
				['shop'] = 'pdm',
			},
			['m3e36'] = {
				['name'] = 'M3 E36',
				['brand'] = 'BMW',
				['model'] = 'm3e36',
				['price'] = 36000,
				['category'] = 'import',
				['hash'] = `m3e36`,
				['shop'] = 'pdm',
			},
			['audquattros'] = {
				['name'] = 'Quattros',
				['brand'] = 'Audi',
				['model'] = 'audquattros',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `audquattros`,
				['shop'] = 'pdm',
			},
			['rs520'] = {
				['name'] = 'rs520',
				['brand'] = 'Audi',
				['model'] = 'rs520',
				['price'] = 145000,
				['category'] = 'import',
				['hash'] = `rs520`,
				['shop'] = 'pdm',
			},
			['r820'] = {
				['name'] = 'R820',
				['brand'] = 'Audi',
				['model'] = 'R820',
				['price'] = 210000,
				['category'] = 'import',
				['hash'] = `r820`,
				['shop'] = 'pdm',
			},
			['bbentayga'] = {
				['name'] = 'bentayga',
				['brand'] = 'Bentley',
				['model'] = 'bbentayga',
				['price'] = 177000,
				['category'] = 'import',
				['hash'] = `bbentayga`,
				['shop'] = 'pdm',
			},
			['bentaygast'] = {
				['name'] = 'bentaygast',
				['brand'] = 'Bentley',
				['model'] = 'bentaygast',
				['price'] = 220000,
				['category'] = 'import',
				['hash'] = `bentaygast`,
				['shop'] = 'pdm',
			},
			['m5e60'] = {
				['name'] = 'm5e60',
				['brand'] = 'Bmw',
				['model'] = 'M5e60',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `m5e60`,
				['shop'] = 'pdm',
			},
			['m4c'] = {
				['name'] = 'm4c',
				['brand'] = 'Bmw',
				['model'] = 'M4',
				['price'] = 78000,
				['category'] = 'import',
				['hash'] = `m4c`,
				['shop'] = 'pdm',
			},
			['e46'] = {
				['name'] = 'e46',
				['brand'] = 'Bmw',
				['model'] = 'm3e46',
				['price'] = 38000,
				['category'] = 'import',
				['hash'] = `e46`,
				['shop'] = 'pdm',
			},
			['e92'] = {
				['name'] = 'e92',
				['brand'] = 'Bmw',
				['model'] = 'M3e92',
				['price'] = 47000,
				['category'] = 'import',
				['hash'] = `e92`,
				['shop'] = 'pdm',
			},
			['bmci'] = {
				['name'] = 'bmci',
				['brand'] = 'Bmw',
				['model'] = 'f90',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `bmci`,
				['shop'] = 'pdm',
			},
			['m3f80'] = {
				['name'] = 'm3f80',
				['brand'] = 'Bmw',
				['model'] = 'f80',
				['price'] = 72000,
				['category'] = 'import',
				['hash'] = `m3f80`,
				['shop'] = 'pdm',
			},
			['m6f13'] = {
				['name'] = 'm6f13',
				['brand'] = 'Bmw',
				['model'] = 'f13',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `m6f13`,
				['shop'] = 'pdm',
			},
			['x5e53'] = {
				['name'] = 'x5e53',
				['brand'] = 'Bmw',
				['model'] = 'e53',
				['price'] = 17000,
				['category'] = 'import',
				['hash'] = `x5e53`,
				['shop'] = 'pdm',
			},
			['fleet78'] = {							--DLC
				['name'] = 'fleet78',
				['brand'] = 'cadillac',
				['model'] = 'fleetwood',
				['price'] = 60000,
				['category'] = 'import',
				['hash'] = `fleet78`,
				['shop'] = 'pdm',
			},
			['cats'] = {							--DLC
				['name'] = 'cats',
				['brand'] = 'cadillac',
				['model'] = 'Ats',
				['price'] = 60000,
				['category'] = 'import',
				['hash'] = `cats`,
				['shop'] = 'pdm',
			},
			['impala59c'] = {							--DLC
				['name'] = 'impala59c',
				['brand'] = 'Chevrolet',
				['model'] = 'impala59c',
				['price'] = 64000,
				['category'] = 'import',
				['hash'] = `impala59c`,
				['shop'] = 'pdm',
			},
			['demon'] = {
				['name'] = 'demon',
				['brand'] = 'Dodge',
				['model'] = 'demon',
				['price'] = 86000,
				['category'] = 'import',
				['hash'] = `demon`,
				['shop'] = 'pdm',
			},
			['f812'] = {
				['name'] = 'f812',
				['brand'] = 'Ferrari',
				['model'] = 'f812',
				['price'] = 320000,
				['category'] = 'import',
				['hash'] = `f812`,
				['shop'] = 'pdm',
			},
			--- import
			['fct'] = {
				['name'] = 'fct',
				['brand'] = 'Ferrari',
				['model'] = 'californiat',
				['price'] = 202000,
				['category'] = 'import',
				['hash'] = `fct`,
				['shop'] = 'pdm',
			},
			['laferrari'] = {
				['name'] = 'laferrari',
				['brand'] = 'Ferrari',
				['model'] = 'laferrari',
				['price'] = 1400000,
				['category'] = 'import',
				['hash'] = `laferrari`,
				['shop'] = 'pdm',
			},
			['f150'] = {
				['name'] = 'f150',
				['brand'] = 'Ford',
				['model'] = 'f150',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `f150`,
				['shop'] = 'pdm',
			},
			['fk8'] = {
				['name'] = 'fk8',
				['brand'] = 'Honda',
				['model'] = 'fk8',
				['price'] = 38000,
				['category'] = 'import',
				['hash'] = `fk8`,
				['shop'] = 'pdm',
			},
			['honcrx91'] = {
				['name'] = 'honcrx91',
				['brand'] = 'Honda',
				['model'] = 'crx91',
				['price'] = 15000,
				['category'] = 'import',
				['hash'] = `honcrx91`,
				['shop'] = 'pdm',
			},
			['na1'] = {
				['name'] = 'na1',
				['brand'] = 'Honda',
				['model'] = 'jackal',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `na1`,
				['shop'] = 'pdm',
			},
			['na6'] = {
				['name'] = 'na6',
				['brand'] = 'Mazda',
				['model'] = 'Miata',
				['price'] = 20000,
				['category'] = 'import',
				['hash'] = `na6`,
				['shop'] = 'pdm',
			},	
			['fd'] = {
				['name'] = 'fd',
				['brand'] = 'Mazda',
				['model'] = 'rx7',
				['price'] = 33000,
				['category'] = 'import',
				['hash'] = `fd`,
				['shop'] = 'pdm',
			},
			['demonhawk'] = {
				['name'] = 'demonhawk',
				['brand'] = 'm',
				['model'] = 'demonhawk',
				['price'] = 110000,
				['category'] = 'sedans',
				['hash'] = `demonhawk`,
				['shop'] = 'pdm',
			},
			['srt8'] = {
				['name'] = 'srt8',
				['brand'] = 'Jeep',
				['model'] = 'srt8',
				['price'] = 71000,
				['category'] = 'sedans',
				['hash'] = `srt8`,
				['shop'] = 'pdm',
			},
			['ccx'] = {
				['name'] = 'ccx',
				['brand'] = 'Koenigsegg',
				['model'] = 'ccx',
				['price'] = 700000,
				['category'] = 'import',
				['hash'] = `ccx`,
				['shop'] = 'pdm',
			},
			['agerars'] = {
				['name'] = 'agerars',
				['brand'] = 'Koenigsegg',
				['model'] = 'Agera RS',
				['price'] = 2555000,
				['category'] = 'import',
				['hash'] = `agerars`,
				['shop'] = 'pdm',
			},
			['lp700r'] = {
				['name'] = 'lp700r',
				['brand'] = 'Lamborghini',
				['model'] = 'lp700r',
				['price'] = 400000,
				['category'] = 'import',
				['hash'] = `lp700r`,
				['shop'] = 'pdm',
			},
			['650s'] = {
				['name'] = '650s',
				['brand'] = 'Mclaren',
				['model'] = '650s',
				['price'] = 260000,
				['category'] = 'import',
				['hash'] = `650s`,
				['shop'] = 'pdm',
			},
			['675lt'] = {
				['name'] = '675lt',
				['brand'] = 'Mclaren',
				['model'] = '675lt',
				['price'] = 350000,
				['category'] = 'import',
				['hash'] = `675lt`,
				['shop'] = 'pdm',
			},
			['W463a1'] = {
				['name'] = 'W463a1',
				['brand'] = 'Mercedes',
				['model'] = 'G63',
				['price'] = 155000,
				['category'] = 'import',
				['hash'] = `W463a1`,
				['shop'] = 'pdm',
			},
			['w140s600'] = {
				['name'] = 'w140s600',
				['brand'] = 'Mercedes',
				['model'] = 'w140',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `w140s600`,
				['shop'] = 'pdm',
			},
			['e55'] = {
				['name'] = 'e55',
				['brand'] = 'Mercedes',
				['model'] = 'w210',
				['price'] = 47000,
				['category'] = 'import',
				['hash'] = `e55`,
				['shop'] = 'pdm',
			},
			['amggtrr20'] = {
				['name'] = 'amggtrr20',
				['brand'] = 'Mercedes',
				['model'] = 'amggtr',
				['price'] = 190000,
				['category'] = 'import',
				['hash'] = `amggtrr20`,
				['shop'] = 'pdm',
			},
			['e400'] = {							--DLC +set sv_enforceGameBuild 2372
				['name'] = 'e400',
				['brand'] = 'Mercedes',
				['model'] = 'e400',
				['price'] = 62000,
				['category'] = 'import',
				['hash'] = `e400`,
				['shop'] = 'pdm',
			},
			['R32'] = {
				['name'] = 'r32',
				['brand'] = 'Nissan',
				['model'] = 'r32',
				['price'] = 41000,
				['category'] = 'import',
				['hash'] = `r32`,
				['shop'] = 'pdm',
			},
			['s15'] = {
				['name'] = 's15',
				['brand'] = 'Nissan',
				['model'] = 'S15',
				['price'] = 29000,
				['category'] = 'import',
				['hash'] = `s15`,
				['shop'] = 'pdm',
			},
			['180sx'] = {		--DLC +set sv_enforceGameBuild 2545
				['name'] = '180sx',
				['brand'] = 'Nissan',
				['model'] = '180sx',
				['price'] = 23000,
				['category'] = 'import',
				['hash'] = `180sx`,
				['shop'] = 'pdm',
			},
			['gtr'] = { 	 	--DLC +set sv_enforceGameBuild 2545
				['name'] = 'gtr',
				['brand'] = 'Nissan',
				['model'] = 'gtr',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `gtr`,
				['shop'] = 'pdm',
			},	
			--- import
			['skyline'] = {
				['name'] = 'skyline',
				['brand'] = 'Nissan',
				['model'] = 'R34',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `skyline`,
				['shop'] = 'pdm',
			},
			['dawnonyx'] = {
				['name'] = 'dawnonyx',
				['brand'] = 'Rolsroyce',
				['model'] = 'dawnonyx',
				['price'] = 380000,
				['category'] = 'import',
				['hash'] = `dawnonyx`,
				['shop'] = 'pdm',
			},
			['wraith'] = {
				['name'] = 'wraith',
				['brand'] = 'Rolsroyce',
				['model'] = 'wraith',
				['price'] = 345000,
				['category'] = 'import',
				['hash'] = `wraith`,
				['shop'] = 'pdm',
			},
			['subwrx'] = {
				['name'] = 'subwrx',
				['brand'] = 'Subaru',
				['model'] = 'wrxsti',
				['price'] = 31000,
				['category'] = 'import',
				['hash'] = `subwrx`,
				['shop'] = 'pdm',
			},
			['cruisersj'] = {
				['name'] = 'cruisersj',
				['brand'] = 'Toyota',
				['model'] = 'landcruiser',
				['price'] = 85000,
				['category'] = 'import',
				['hash'] = `cruisersj`,
				['shop'] = 'pdm',
			},
			['a80'] = {
				['name'] = 'a80',
				['brand'] = 'Toyota',
				['model'] = 'a80',
				['price'] = 43000,
				['category'] = 'import',
				['hash'] = `a80`,
				['shop'] = 'pdm',
			},
			--- import
			['huayrar'] = {
				['name'] = 'huayrar',
				['brand'] = 'Pagani',
				['model'] = 'huayrar',
				['price'] = 3500000,
				['category'] = 'import',
				['hash'] = `huayrar`,
				['shop'] = 'pdm',
			},
			['stelvio'] = {
				['name'] = 'stelvio',
				['brand'] = 'Alfaromeo',
				['model'] = 'stelvio',
				['price'] = 90000,
				['category'] = 'import',
				['hash'] = `stelvio`,
				['shop'] = 'pdm',
			},
			['volvo145'] = {
				['name'] = 'volvo145',
				['brand'] = 'Volvo',
				['model'] = 'volvo145',
				['price'] = 14000,
				['category'] = 'import',
				['hash'] = `volvo145`,
				['shop'] = 'pdm',
			},
			['xkgt'] = {
				['name'] = 'xkgt',
				['brand'] = 'xkgt',
				['model'] = 'Jaguar',
				['price'] = 174000,
				['category'] = 'import',
				['hash'] = `xkgt`,
				['shop'] = 'pdm',
			},
			-- donat
			['g63topcar'] = {
				['name'] = 'g63topcar',
				['brand'] = 'Mercedes Benz',
				['model'] = 'g63topcar',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `g63topcar`,
				['shop'] = 'pdm',
			},
			['m4c'] = {
				['name'] = 'm4c',
				['brand'] = 'BMW M4C',
				['model'] = 'm4c',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `m4c`,
				['shop'] = 'pdm',
			},
			['rmodgt63'] = {
				['name'] = 'rmodgt63',
				['brand'] = 'Mercedes Benz G63',
				['model'] = 'rmodgt63',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmodgt63`,
				['shop'] = 'pdm',
			},
			['m5'] = {
				['name'] = 'm5',
				['brand'] = 'BMW m5',
				['model'] = 'm5',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `m5`,
				['shop'] = 'pdm',
			},
			['rmode63s'] = {
				['name'] = 'rmode63s',
				['brand'] = 'Mercedes 63s',
				['model'] = 'rmode63s',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmode63s`,
				['shop'] = 'pdm',
			},
			['rmod69police'] = {
				['name'] = 'rmod69police',
				['brand'] = 'Challanger 69',
				['model'] = 'rmod69police',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmod69police`,
				['shop'] = 'pdm',
			},
			['rmodbmwm8'] = {
				['name'] = 'rmodbmwm8',
				['brand'] = 'BMW M8',
				['model'] = 'rmodbmwm8',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmodbmwm8`,
				['shop'] = 'pdm',
			},
			['rmodg65'] = {
				['name'] = 'rmodg65',
				['brand'] = 'Mercedes Benz G65',
				['model'] = 'rmodg65',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmodg65`,
				['shop'] = 'pdm',
			},
			['amggtr20'] = {
				['name'] = 'amggtr20',
				['brand'] = 'Mercedez Benz GTR',
				['model'] = 'amggtr20',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `amggtr20`,
				['shop'] = 'pdm',
			},
			['rmodsuprapandem'] = {
				['name'] = 'rmodsuprapandem',
				['brand'] = 'Toyota Supra Pandem',
				['model'] = 'rmodsuprapandem',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `rmodsuprapandem`,
				['shop'] = 'pdm',
			},
			['fct'] = {
				['name'] = 'fct',
				['brand'] = 'Ferrari',
				['model'] = 'fct',
				['price'] = 4000,
				['category'] = 'Donation',
				['hash'] = `fct`,
				['shop'] = 'pdm',
			},