Config = {}

Config.Crafting = {
    {
        itemName = "lockpick",
        isGun = false,
        level = 0,
        levelUp = 9,
        Timer = 3000,
        NeedItems = {
            ["plastic"] = 52,
            ["steel"] = 40,
        },
    },
    {
        itemName = "radioscanner",
        isGun = false,
        level = 0,
        levelUp = 10,
        Timer = 3000,
        NeedItems = {
            ["plastic"] = 52,
            ["steel"] = 40,
        },
    },
    {
        itemName = "screwdriverset",
        isGun = false,
        level = 0,
        levelUp = 9,
        Timer = 3000,
        NeedItems = {
            ["plastic"] = 52,
            ["steel"] = 40,
        },
    },
    {
        itemName = "handcuffs",
        isGun = false,
        level = 140,
        levelUp = 13,
        Timer = 3000,
        NeedItems = {
            ["steel"] = 24,
            ["aluminum"] = 28,
        },
    },
    {
        itemName = "pistol_ammo",
        isGun = false,
        level = 160,
        levelUp = 10,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 30,
            ["steel"] = 45,
            ["copper"] = 34,
        },
    },
    {
        itemName = "armor",
        isGun = false,
        level = 170,
        levelUp = 7,
        Timer = 3000,
        NeedItems = {
            ["steel"] = 65,
            ["plastic"] = 45,
            ["aluminum"] = 35,
        },
    },
    {
        itemName = "drill",
        isGun = false,
        level = 180,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["screwdriverset"] = 3,
			["steel"] = 50,
			["advancedlockpick"] = 2,
        },
    },
    {
        itemName = "snspistol_part_1",
        isGun = false,
        level = 190,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 20,
            ["plastic"] = 35,
            ["steel"] = 20,
            ["iron"] = 40,
        },
    },
    {
        itemName = "snspistol_part_2",
        isGun = false,
        level = 200,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 25,
            ["plastic"] = 40,
            ["steel"] = 25,
            ["iron"] = 35,
            ["copper"] = 15,
        },
    },
    {
        itemName = "thermite",
        isGun = false,
        level = 250,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["iron"] = 50,
			["plastic"] = 44,
			["aluminum"] = 60,
        },
    },
    {
        itemName = "snspistol_part_3",
        isGun = false,
        level = 260,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 35,
            ["plastic"] = 30,
            ["steel"] = 15,
            ["copper"] = 15,
        },
    },
    {
        itemName = "snspistol_stage_1",
        isGun = false,
        level = 280,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["screwdriverset"] = 2,
			["snspistol_part_1"] = 1,
			["snspistol_part_3"] = 1,
			["snspistol_part_2"] = 1,
        },
    },
    {
        itemName = "weapon_snspistol",
        isGun = false,
        level = 280,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["screwdriverset"] = 2,
			["advancedlockpick"] = 2,
			["snspistol_part_1"] = 1,
			["snspistol_part_3"] = 1,
			["snspistol_part_2"] = 1,
            ["snspistol_stage_1"] = 1,
        },
    },
    {
        itemName = "laptop_green",
        isGun = false,
        level = 270,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["iron"] = 50,
			["plastic"] = 44,
			["aluminum"] = 60,
        },
    },
    {
        itemName = "weapon_vintagepistol",
        isGun = false,
        level = 300,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["snspistol_part_1"] = 1,
		    ["snspistol_part_2"] = 1,
		    ["snspistol_part_3"] = 1,
		    ["screwdriverset"] = 2,
		    ["advancedlockpick"] = 2,
        },
    },
    {
        itemName = "weapon_pistol",
        isGun = false,
        level = 320,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
           ["snspistol_part_1"] = 1,
		   ["snspistol_part_2"] = 1,
		   ["snspistol_part_3"] = 2,
		   ["screwdriverset"] = 5,
		   ["advancedlockpick"] = 3,
        },
    },
    {
        itemName = "weapon_stickybomb",
        isGun = false,
        level = 370,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["screwdriverset"] = 3,
            ["plastic"] = 90,
            ["steel"] = 50,
            ["copper"] = 70,
			["iron"] = 100,
			["thermite"] = 2,
        },
    },
    {
        itemName = "weapon_appistol",
        isGun = false,
        level = 380,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["snspistol_part_1"] = 1,
			["snspistol_part_2"] = 2,
			["snspistol_part_3"] = 3,
			["screwdriverset"] = 3,
			["advancedlockpick"] = 3,
        },
    },
    {
        itemName = "smg_ammo",
        isGun = false,
        level = 390,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 50,
            ["steel"] = 60,
            ["copper"] = 40,
        },
    },
    {
        itemName = "weapon_microsmg2",
        isGun = true,
        level = 450,
        levelUp = 17,
        Timer = 3000,
        NeedItems = {
            ["metalscrap"] = 160,
            ["steel"] = 210,
            ["copper"] = 110,
			["screwdriverset"] = 3,
			["advancedlockpick"] = 6,
        },
    },
}

Config.Tunershop = {
    {
        itemName = "engine0",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 10,
            ['steel'] = 10,
        },
    },
    {
        itemName = "engine1",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 100,
            ['steel'] = 150,
            ['rubber'] = 105,
        },
    },
    {
        itemName = "engine2",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 115,
            ['steel'] = 170,
            ['rubber'] = 120,
        },
    },
    {
        itemName = "engine3",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 80,
            ['steel'] = 130,
            ['rubber'] = 90,
        },
    },
    {
        itemName = "engine4",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 150,
            ['steel'] = 200,
            ['rubber'] = 140,
        },
    },
    {
        itemName = "transmission0",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 70,
            ['steel'] = 70,
            ['rubber'] = 50,
        },
    },
    {
        itemName = "transmission1",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 90,
        ['steel'] = 80,
        ['rubber'] = 80,
        },
    },
    {
        itemName = "transmission2",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 105,
        ['steel'] = 100,
        ['rubber'] = 90,
        },
    },
    {
        itemName = "transmission3",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 125,
        ['steel'] = 110,
        ['rubber'] = 105,
        },
    },
    {
        itemName = "brake0",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 40,
        ['steel'] = 25,
        ['rubber'] = 100,
        },
    },
    {
        itemName = "brake1",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 50,
        ['steel'] = 30,
        ['rubber'] = 120,
        },
    },
    {
        itemName = "brake2",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 40,
        ['steel'] = 25,
        ['rubber'] = 100,
        },
    },
    {
        itemName = "brake3",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 45,
        ['steel'] = 35,
        ['rubber'] = 140,
        },
    },
    {
        itemName = "turbo0",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 10,
        ['steel'] = 10,
        },
    },
    {
        itemName = "turbo1",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 130,
        ['steel'] = 170,
        ['rubber'] = 20,
        },
    },
    {
        itemName = "suspension0",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 60,
        ['steel'] = 50,
        },
    },
    {
        itemName = "suspension1",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 80,
        ['steel'] = 40,
        ['rubber'] = 110,
        },
    },
    {
        itemName = "suspension2",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 90,
            ['steel'] = 55,
            ['rubber'] = 115,
        },
    },
    {
        itemName = "suspension3",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 105,
        ['steel'] = 60,
        ['rubber'] = 125,
        },
    },
    {
        itemName = "suspension4",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 3000,
        NeedItems = {
            ['aluminum'] = 125,
        ['steel'] = 90,
        ['rubber'] = 140,
        },
    },
    {
        itemName = "advancedrepairkit",
        isGun = false,
        level = 0,
        levelUp = 2,
        Timer = 3000,
        NeedItems = {
            ['plastic'] = 50,
            ["metalscrap"] = 60,
            ["steel"] = 85,
        },
    },
}

Config.TradeMat = {
    {
        itemName = "plastic",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "rubber",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "metalscrap",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "steel",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "glass",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "iron",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "copper",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
    {
        itemName = "aluminum",
        isGun = false,
        level = 0,
        levelUp = 0,
        Timer = 100,
        NeedItems = {
            ['recyclablematerial'] = 1,
        },
    },
}