Config = {}

Config.Locations = {
    ['shop'] = { ['x'] = -527.5286, ['y'] = -582.7517, ['z'] = 34.681808, ['h'] = 176.85447 },
	['boss'] = { ['x'] = 177.40003, ['y'] = -1322.084, ['z'] = 24.029901, ['h'] = 255.87939  },
}


Config.Sells = {
    { item = "iphone", price = 400 },
    { item = "samsung_s8", price = 400 },
    { item = "samsungphone", price = 400 },
    { item = "laptop", price = 400 },
}

Config.Items = {
    label = "Pawnshop",
    slots = 1,
    items = {
        [1] = {
            name = "phone",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
		},
        [2] = {
            name = "fitbit",
            price = 50,
            amount = 150,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "laptop",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "tequilashot",
            price = 0,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "boombox",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
		},
        [6] = {
            name = "box",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "duffelbag",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "toolbox",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
		},
        [9] = {
            name = "heavyarmor",
            price = 650,
            amount = 100,
            info = {},
            type = "item",
            slot = 9,
		},
        [10] = {
            name = "weapon_crowbar",
            price = 235,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
		},
        [11] = {
            name = "vpn",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "lockpick",
            price = 75,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "advancedlockpick",
            price = 560,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "head_mask",
            price = 1330,
            amount = 10,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "caraudiosystem",
            price = 1025,
            amount = 10,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "fishingrod",
            price = 330,
            amount = 10,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "towing_rope",
            price = 6745,
            amount = 10,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "parachute",
            price = 110,
            amount = 10,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "diving_gear",
            price = 1095,
            amount = 5,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "nightvision",
            price = 5300,
            amount = 1,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "harness",
            price = 6590,
            amount = 1,
            info = {},
            type = "item",
            slot = 21,
        },
    }
}
